# http://openhome.cc/Gossip/JavaGossip-V1/Package.htm

build:
	javac -d ../ ../Point2D.java 
	javac -d ../ -cp "../:$$CLASSPATH" ../UsePackage.java 

run:
	java -cp "../:$$CLASSPATH" onlyfun.caterpillar.UsePackage
